// Generated by uniffi-bindgen-react-native
#include "react-native-iptelly.h"
#include "generated/iptelly_ffi.hpp"

namespace iptelly {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeIptellyFfi::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}